// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYOi7VnI04B3e5iHjT6cLyyT9L1Gprzn8',
    appId: '1:71608197927:web:d172b8d7a79965d43a3f02',
    messagingSenderId: '71608197927',
    projectId: 'grocery-app-73d48',
    authDomain: 'grocery-app-73d48.firebaseapp.com',
    storageBucket: 'grocery-app-73d48.appspot.com',
    measurementId: 'G-E3LWH6W5Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJkRDYwNPDRl7qvD-kxbzTTxjSkCyQhmA',
    appId: '1:71608197927:android:f00937a713199dde3a3f02',
    messagingSenderId: '71608197927',
    projectId: 'grocery-app-73d48',
    storageBucket: 'grocery-app-73d48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHvXpf1eEDvOaY-IcGW4mU2fQ5_o_qGRc',
    appId: '1:71608197927:ios:e9bb94590b3c3d213a3f02',
    messagingSenderId: '71608197927',
    projectId: 'grocery-app-73d48',
    storageBucket: 'grocery-app-73d48.appspot.com',
    iosBundleId: 'com.example.groceryApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHvXpf1eEDvOaY-IcGW4mU2fQ5_o_qGRc',
    appId: '1:71608197927:ios:6c77fa681b574d453a3f02',
    messagingSenderId: '71608197927',
    projectId: 'grocery-app-73d48',
    storageBucket: 'grocery-app-73d48.appspot.com',
    iosBundleId: 'com.example.groceryApp1.RunnerTests',
  );
}
